### ISSUE TITLE
need basic info in about page for each member

### ISSUE THREAD

**Issue by bsy6766** [dm37537/cs373-idb#18]
Here's the required fields for each member. This gonna change through updates.

for each member:  
photo: either file or link to image will do
bio: In general, use it to advertise yourself and how your skills relate to the website you've built.
major responsibilities: what you did on this project
no. of commits: -
no. of issues: -
no. of unit tests: -
stats: 
- total no. of commits: -
- total no. of issues: -
- total no. of unit tests: -

**Comment by o0tomato0o** [comment]
Name: Jin Kim
UTEID: JHK924
CSLogin: JHK924
Photo: http://tinypic.com/r/1zovt6u/8
Bio: Computer Science major, Korean minor, Graduating on May 2015. Fluent in Java, C, Python, SQL.
Major Responsibilities: Apiary Contribution, data entry, etc
no. of commits: TBA
no. of issues: TBA
no. of unit Tests: TBA

**Comment by sparkhee93** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/6036105/6655768/702606d8-cad9-11e4-8a6b-281a833cc9cc.jpg)

Bio: BSA in Computer Science with a Business Foundations Certificate. Expected to graduate May 2015. Language: Java, C, C#, Python, SQL
Major Responsibilities: Front-end development (HTML, CSS, JavaScript) with usage of Twitter Bootstrap

**Comment by dm37537** [comment]
![2014-11-21](https://cloud.githubusercontent.com/assets/8682794/6788799/a47d17da-d161-11e4-9aa2-50d203384b94.jpg)

Bio: BS in Computer Science. Expected to graduate Dec 2015.
Language: Java, C++, PHP, SQL, Python
Major Responsibilities: Team leader, assigning work to each team member, helping communication within the team, collecting data, designing pages.

**Comment by Kevin-Valle** [comment]
![facebook_-1038389358](https://cloud.githubusercontent.com/assets/5411883/6817721/b077951c-d272-11e4-9354-40cbf0cca5cd.jpg)

Bio: Third year University of Texas student pursuing Bachelor of Science degrees in Computer Science and Pure Mathematics. Expected to graduate in August 2015. Favorite Language is Python.
Major Responsibilities: Setting up Rackspace server, implementing API, designing models, and testing said models.

**Comment by bsy6766** [comment]
Thanks yall
