### ISSUE TITLE
Jobs.json having incorrect values

### ISSUE THREAD

**Issue by sparkhee93** [dm37537/cs373-idb#21]
For id: 8, it's supposed to be a Oracle job post but the description is describing a job for Amazon.

I've find a few like this and will post more when I get through them.

**Comment by sparkhee93** [comment]
Nevermind, I think I read it the values wrong.

**Comment by bsy6766** [comment]
Job 8, 
Company ID is 3(Amazon)
and Description is about Prime Amazon
but the link is to Oracle.

**Comment by bsy6766** [comment]
The link leads to Software Developer 2 job page
