### ISSUE TITLE
Unit Test Page

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#33]
There needs to be a page that, when visited, runs the unit tests in tests.py on the backend and returns the output to the frontend. There is currently some attempt at this already in programmerJobs.py.
- Make sure to use the /tests endpoint
- Running the tests just involves running the command "python tests.py"

**Comment by bsy6766** [comment]
working on this, seems like working. I'll push soon

**Comment by bsy6766** [comment]
ok Pushed,
Few minor change here, 
first of all, added Unittest button on navbar, if you click, you will see the /tests page, wait the server to run  tests.py on subprocess, and redirects the window to /result page, which is gonna show the result of the unittest.
