### ISSUE TITLE
Make Locations Page Dynamic

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#39]
This involves making a copy of the locations.html page and placing it in the templates folder.
Don't delete the version in the static folder until we are sure that the dynamic version works.

Replace any static content with model code.

Example:
"This is the description for Austin" becomes location.description where location is an object bound to the method in programmerobs.py for the location page.

Reference http://jinja.pocoo.org/docs/dev/templates/ if you have any questions.

**Comment by bsy6766** [comment]
All dynamic, just need to check if it works with db
