### ISSUE TITLE
Make a Dynamic Page All Languages

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#40]
This involves making a copy of the a specific language's page and placing it in the templates folder.
Don't delete the version in the static folder until we are sure that the dynamic version works.

Replace any static content with model code.

Example:
"This is the description for Java" becomes language.description where language is an object bound to the method in programmerobs.py for the language page.

Reference http://jinja.pocoo.org/docs/dev/templates/ if you have any questions.

**Note that there should only be one page that serves all the languages not one for each separate language

**Comment by bsy6766** [comment]
I'm working on this

**Comment by bsy6766** [comment]
Made language's home page dynamic.

Rank and Icons are displayed dynamically based on Rank.json and Language.json

**Comment by bsy6766** [comment]
Changed languages.html to language_home.html

Working on language.html to dynamically hold all the language pages since the design format is same and etc

**Comment by bsy6766** [comment]
Now language.html's image is dynamic.

**Comment by bsy6766** [comment]
All language pages are dynamic except navbar.

**Comment by bsy6766** [comment]
All dynamic, just need to check if it works with db

**Comment by Kevin-Valle** [comment]
Hey, I have a couple of questions regarding the languages JSON.

Are you using both the description and the wiki description? Should this be reflected in the models?
Do you need the wikipedia link to be stored in the model?

These questions are the only thing left before the data can finish being inserted

**Comment by bsy6766** [comment]
Currently we are only using wiki's descriptions.

**Comment by bsy6766** [comment]
And wiki link aswell

**Comment by Kevin-Valle** [comment]
Ok, i will change the insert statements and follow up later today
