### ISSUE TITLE
Make a Dynamic Page All Jobs

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#42]
This involves making a copy of the a specific job's page and placing it in the templates folder.
Don't delete the version in the static folder until we are sure that the dynamic version works.

Replace any static content with model code.

Example:
"This is the description for Software Developer" becomes job.description where job is an object bound to the method in programmerobs.py for the job page.

Reference http://jinja.pocoo.org/docs/dev/templates/ if you have any questions.

**Note that there should only be one page that serves all the jobs not one for each separate job

**Comment by bsy6766** [comment]
All dynamic, just need to check if it works with db
