### ISSUE TITLE
Make a Dynamic Page All Locations

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#43]
This involves making a copy of the a specific location's page and placing it in the templates folder.
Don't delete the version in the static folder until we are sure that the dynamic version works.

Replace any static content with model code.

Example:
"This is the description for Austin" becomes location.description where location is an object bound to the method in programmerobs.py for the location page.

Reference http://jinja.pocoo.org/docs/dev/templates/ if you have any questions.

**Note that there should only be one page that serves all the locations not one for each separate location

**Comment by bsy6766** [comment]
working on this lightly

**Comment by bsy6766** [comment]
done

**Comment by bsy6766** [comment]
All dynamic, just need to check if it works with db
