### ISSUE TITLE
Make a Dynamic Page All Skillsets

### ISSUE THREAD

**Issue by Kevin-Valle** [dm37537/cs373-idb#44]
This involves making a copy of the a specific skillset's page and placing it in the templates folder.
Don't delete the version in the static folder until we are sure that the dynamic version works.

Replace any static content with model code.

Example:
"This is the description for Database" becomes skillset.description where skillset is an object bound to the method in programmerobs.py for the skillset page.

Reference http://jinja.pocoo.org/docs/dev/templates/ if you have any questions.

**Note that there should only be one page that serves all the skillsets not one for each separate skillset

**Comment by dm37537** [comment]
Will work on this

**Comment by bsy6766** [comment]
All dynamic, just need to check if it works with db
