### ISSUE TITLE
unavailable id still opening up page

### ISSUE THREAD

**Issue by sparkhee93** [dm37537/cs373-idb#90]
When you manually type in an id beyond what's available, it still opens up.

For example, typing in:
http://104.130.229.90:5000/language/15
It opens up a site without displaying anything.

**Comment by Kevin-Valle** [comment]
So, what I pushed seems to have fixed this issue for everything but language. I will continue to work on this after work today

**Comment by Kevin-Valle** [comment]
All pages will now 404 if the id doesn't exist in the database
